spring:
  datasource:
    #url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/outboxtable_db?allowPublicKeyRetrieval=true&autoReconnect=true
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/concurrency_db?allowPublicKeyRetrieval=true&autoReconnect=true
    username: root
    password: mdymen_pass
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

application:
  lockmanager:
    type: redis
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:localhost}
    release-timeout: 5000

